version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      # Additional installation commands if necessary
      # - echo Installing Docker...
      # - sudo yum update -y
      # - sudo yum install -y docker-ce

pre_build:
  commands:
    - echo "Logging in to Amazon ECR..."
    - REGION=$(aws configure get region)
    - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
    - echo "Region: $REGION"
    - echo "Account: $AWS_ACCOUNT_ID"
    - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
    




  build:
    commands:
      - echo Building Docker image...
      - docker build -t 992382811294.dkr.ecr.ap-northeast-2.amazonaws.com/yr-backend-zicledu:latest .

      - echo Pushing Docker image to Amazon ECR...
      #- docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/yr-backend-zicledu:latest
      - docker push 992382811294.dkr.ecr.ap-northeast-2.amazonaws.com/yr-backend-zicledu:latest
      - echo "Region: $REGION"
      - echo "Account: $AWS_ACCOUNT_ID"

# artifacts:
#   files:
#     - imagedefinitions.json
