version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      # Additional installation commands if necessary
      - echo Installing Docker...
      # - sudo yum update -y
      # - sudo yum install -y docker-ce

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo ${AWS_DEFAULT_REGION}
      - echo ${AWS_ACCOUNT_ID}
      # - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com


  build:
    commands:
      - echo Building Docker image...
      - docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/yr-backend-zicledu:latest .
      - echo Pushing Docker image to Amazon ECR...
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/yr-backend-zicledu:latest

# artifacts:
#   files:
#     - imagedefinitions.json
