version: 0.2

phases:
  install:
    commands:
      - hostname 
      - ip addr
      - apt install aws-cli
 
  pre_build:
    commands:
      # Amazon ECR에 로그인
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 992382811294.dkr.ecr.ap-northeast-2.amazonaws.com
      
  build:
    commands:
      # Docker 이미지 빌드 및 푸시
      - echo Building Docker image...
      - docker build -t ecr:latest .
      - docker images | grep "ecr
      - echo Pushing Docker image to Amazon ECR...
      - docker tag ecr:latest 992382811294.dkr.ecr.ap-northeast-2.amazonaws.com/ecr:latest
      - docker push 992382811294.dkr.ecr.ap-northeast-2.amazonaws.com/ecr:latest


