version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      # Additional installation commands if necessary
      - echo Installing Docker...
      # - sudo yum update -y
      # - sudo yum install -y docker-ce

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo -e`리전: ${AWS_DEFAULT_REGION}`
      - echo -e`계정: ${AWS_ACCOUNT_ID}`
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 992382811294.dkr.ecr.ap-northeast-2.amazonaws.com


  build:
    commands:
      - echo Building Docker image...
      - docker build -t 992382811294.dkr.ecr.ap-northeast-2.amazonaws.com/yr-backend-zicledu:latest .
      - echo Pushing Docker image to Amazon ECR...
      - docker push 992382811294.dkr.ecr.ap-northeast-2.amazonaws.com/yr-backend-zicledu:latest

# artifacts:
#   files:
#     - imagedefinitions.json
